### PR TITLE
Quick fix to silence output (fixes #69)

### LINKED ISSUE #69: Make tests less noisy
Output from the tests is a bit noisy because we have `console.log` calls inside the code path that aren't silenced for tests.

screenshot 2015-10-09 21 00 55

Realistically, we probably want an `validator.config.output` option that is `nothing` or `null`.

Not sure when the CLI would ever want it, but it's what we want for the tests and we should already have the infra for it via that `config.output` option.

Other `console.log` should be silenced by this option. We probably just want to use our own `log` method everywhere.

### PR DESCRIPTION
**Pull request by muffinresearch**
(See #69)

This just stubs the code paths that otherwise lead to output.

### CODE REVIEW

File: tests/test.validator.js [hunk 1]
```diff
@@ -103,6 +103,7 @@ describe('Validator', function() {
   // - install.rdf
   it('should send JSScanner messages to the collector', () => {
     var addonValidator = new Validator({_: ['tests/example.xpi']});
+    addonValidator.print = sinon.stub();
```
Comment (tofumatt) [inline tests/test.validator.js]: A comment to explain why we're doing this would be handy for the future. Normally I assume stubbing methods is for testing purposes, but this is really just a flourish so it'd be good to clarify why it's here.

**Comment by tofumatt** [comment]
r+wc

I'm actually not sure why we'd want to be more robust in the future (when would we need a validator that didn't output anything? ^_^). I'd say this should do for awhile. :+1:

File: tests/test.validator.js (hunk 1 above)
Comment (muffinresearch) [inline tests/test.validator.js]: Yep - good call.
