### PR TITLE
Fix error handling with --metadata

### LINKED ISSUE #304: Fix bug in metadata arg

### PR DESCRIPTION
**Pull request by muffinresearch**
The end of the promise chain for metadata handling was missing a catch. I also refactored handleError to DRY things up a bit.

Fixes #304

### CODE REVIEW

File: src/validator.js [hunk 1]
```diff
@@ -387,7 +395,7 @@ export default class Validator {
       });
   }
 
-  scan(_Xpi=Xpi) {
+  scan(_Xpi=Xpi, _console=console) {
```
Comment (tofumatt) [inline src/validator.js]: :+1:

**Comment by tofumatt** [comment]
r+
